app/__init__.py
from flask import Flask
from config import Config
from flask_bootstrap import Bootstrap
import os
from logging.handlers import RotatingFileHandler
import logging


bootstrap = Bootstrap()


def create_app(config_class=Config):
    """
    Constructs a Flask application instance.

    Parameters
    ----------
    config_class: class that stores the configuration variables.

    Returns
    -------
    app : Flask application
    """
    app = Flask(__name__)
    app.config.from_object(config_class)
    bootstrap.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.api import bp as api_bp
    app.register_blueprint(api_bp, url_prefix='/api')

    if not os.path.exists('logs'):
        os.mkdir('logs')
        file_handler = RotatingFileHandler('logs/oslo-bysykkel-monitor.log',
                                           maxBytes=10240, backupCount=10)
        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s '
            '[in %(pathname)s:%(lineno)d]'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)
    app.logger.setLevel(logging.INFO)
    app.logger.info('Oslo Bysykkel Monitor startup')
    return app

app/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from app.api import stations

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from werkzeug.utils import redirect
from flask import render_template, flash
from app.main import bp
from app.main.streamer import StationStreamer


@bp.route('/')
@bp.route('/index')
def index():
    """
    Renders the home page of the application.
    """
    try:
        api = StationStreamer()
        stations, last_updated = api.select_data()
        return render_template('index.html', stations=stations, last_updated=last_updated)
    except:
        flash("Not possible to retrieve data from the API. "
              "Please contact the administrator")


@bp.route('/linkedin_profile')
def linkedin_profile():
    """
    Renders the profile page of the application's author.
    """
    return redirect("https://www.linkedin.com/in/flaviasouzasantos")


@bp.route('/oslo_byssykkel')
def oslo_bysykkel():
    """
    Renders the home page for Oslo Bysykkel.
    """
    return redirect("https://oslobysykkel.no/")

app/templates/base.html
{% extends 'bootstrap/base.html' %}
{% block title %} Oslo Bysykkel Monitor {% endblock title %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Explore all stations</a>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}
        {% block app_content %}{% endblock %}
    </div>
    <br>
    <br>
    <br>
    <br>

    <nav class="navbar navbar-default">
        <div class="container">
            {% include "footer.html" %}
        </div>
    </nav>
{% endblock %}

app/templates/footer.html
<!-- Footer -->
<footer class="page-footer font-small blue">

  <!-- Copyright -->
  <br>
  <br>
    <div class="footer-copyright text-center py-3">Real time data:
    <a href="{{ url_for('main.oslo_bysykkel') }}">Oslo Bysykkel</a>
  </div>
  <div class="footer-copyright text-center py-3">Author:
    <a href="{{ url_for('main.linkedin_profile') }}">Flávia Santos - Systems Engineer | Python developer</a>
  </div>
   <br>

  <!-- Copyright -->

</footer>
<!-- Footer -->

app/templates/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
      <!-- Table -->
      <div class="row">
            <div class="col">
              <div class="card shadow">
                <div class="card-header border-0">
                  <h3 class="mb-0">Oslo Bysykkel Stations</h3>
                    <h7 class="card-title text-muted mb-0">Last updated: {{ last_updated }}</h7>
                    <br>
                </div>
                <div class="table-responsive">
                  <table class="table align-items-center table-flush">
                    <thead class="thead-light">
                      <tr>
                        <th scope="col"></th>
                        <th scope="col">Station</th>
                        <th scope="col">Bikes</th>
                        <th scope="col">Docks</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for station in stations %}
                      <tr>
                        <th scope="row">
                          <div class="media align-items-center">
                            <a href="#" class="avatar rounded-circle mr-3">
                              <img alt="Bike" src="static/assets/img/_bike.jpg"  width="30" height="30">
                            </a>
                          </div>
                        </th>
                            <td>
                              <span class="badge badge-dot mr-4">
                                <span class="h5 mb-0 text-sm">{{ station['name'] }}</span>
                              </span>
                            </td>
                            <td>
                              {{ station['num_bikes_available'] }} available
                            </td>
                            <td>
                              {{ station['num_docks_available'] }} available
                            </td>
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
      </div>
{% endblock %}